### ISSUE TITLE
Relative url paths in node_modules css

### ISSUE THREAD

**Issue by jbccollins** [elycruz/rollup-plugin-sass#23]
Preface: I'm not entirely sure if this is an issue that should be handled by rollup-plugin-sass but I didn't know where else to ask this.

Some npm libraries use relative image url paths in their css (eg. leaflet). I cannot figure out how to get this plugin to respect those relative paths. My js and css live in
src/MyProject/
 - MyProject.js
 - MyProject.css

and I have rollup's destination set to
dist/MyProject/
 - MyProjectOutput.js
 - MyProjectOutput.css

However, the relative paths in the output css are unchanged. So if /node_modules/leaflet/dist/leaflet.css is included in MyProjectOutput.css and it has a path like "url(images/marker-icon.png)" my browser will look for an image at "/dist/images/marker-icon.png" and 404. Any suggestions as to how I might fix that?

**Comment by differui** [comment]
I cloud advise you using [postcss](http://postcss.org/) to twist the url of images.

``` js
import { rollup } from 'rollup';
import sass from 'rollup-plugin-sass';
import postcss from 'rollup-plugin-postcss';

rollup({
  entry: 'main.js',
  plugins: [
    sass(),
    postcss({
      plugins: [
        twistImagesUrl()
      ]
    })
  ]
}).then(...)
```

Checkout the [doc](http://api.postcss.org/postcss.html#.plugin).This is really easy to get your own plugin.

**Comment by jbccollins** [comment]
Ok so this is not something that rollup-plugin-sass is designed to handle? Feel free to close this issue if you don't believe it to be relevant.

**Comment by jbccollins** [comment]
Ok. So good news and bad news.

I was able to write a little plugin that converts my urls which ended up being pretty straightforward. Thanks for the suggestion! It works fine as a standalone postcss-plugin running with gulp but it does not work with the sass processor. The idea is that rollup will check the absolute path of the input file and convert all relative url() tags to be absolute based on the input file path.

My plugin:

``` javascript
var postcss = require('postcss');
var path = require("path");

// Credit: http://stackoverflow.com/a/6582214
var extensionPattern=/\.[0-9a-z]{1,5}$/i;

module.exports = postcss.plugin('myplugin', function () {

  return function (css) {

    css.walkRules(function (rule) {
      rule.walkDecls(function (decl, i) {
        var value = decl.value;
        if (value.indexOf( 'url(' ) !== -1) {
          // Get the url requested by matching the string inside the brackets of url().
          // Then replace any double or single quotes therein.
          var urlPath = value.match(/\(([^)]+)\)/)[1].replace(/["']/g, "");

          // Check against the regex for file extensions
          var urlExtension = urlPath.match(extensionPattern);

          // No extension implies that the the url is a dataURI.
          // Starting with '/' means that the url is already absolute.
          if (!urlExtension || urlPath.toString().startsWith('/')) {
            return;
          }
          // Strip the file name from the input file path
          var inputFilePath = css.source.input.file.replace(/[^\/]*$/, '');

          // Send the new value back into the stylesheet as an ABSOLUTE path instead of a relative path
          decl.value = 'url("' + path.resolve(inputFilePath  + urlPath) + '")';
        }
      });
    });
  }
});
```

My relevant rollup config:

``` javascript
      sass({
        // Make sure to grab any css needed node_modules
        include: [ 'node_modules/**/*.css', '/my/project/path/**/*.scss'],
        processor(code, id) {
          return postcss([myplugin()])
            .process(code)
            .then((result) => {
              return result.css;
            });
        },
        output(styles, styleNodes) {
           ....
        }
      }),
```

This plugin produces the results I want when just using gulp and postcss without the context of rollup-plugin-sass. eg:
INPUT: 

``` css
.one {
    background-image: url("blah/derp/something.gif");
}
.two {
    background-image: url("paper.png");
}
.three {
    background-image: url(data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7);
}
.four {
    background-image: url("/another.png");
}
.five {
    background-image: url("../../echo.png");
}
```

OUTPUT:

``` css
.one {
    background-image: url("/opt/my/project/path/blah/derp/something.gif");
}
.two {
    background-image: url("/opt/my/project/path/paper.png");
}
.three {
    background-image: url(data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7);
}
.four {
    background-image: url("/another.png");
}
.five {
    background-image: url("/opt/echo.png");
}
```

The problem seems to be that css.source.input.file is undefined. Instead css.source.input.id exists but for my use case that's not helpful. Is there any way I can pass my plugin the actual file path of the input css?
